### ISSUE TITLE
NA with factor variables

### ISSUE THREAD

**Issue by richardangell** [richardangell/GbmExplainR#20]
Example from decompose_gbm_prediction function results in the following error; Error in decompose_gbm_prediction(gbm1, data[1, ]) : ‘NA’ is not an expected level for X4

**Comment by richardangell** [comment]
attempted fix in [24bc9f3](https://github.com/richardangell/GbmExplainR/commit/24bc9f3b575289b63885d7f28e751f8553948d90) but results in another error if factor level is NA; Error in if (cat_value != "NA") { : missing value where TRUE/FALSE needed

**Comment by richardangell** [comment]
Fixed in #22

**Comment by adriasebastia** [comment]
Hello Richard,

I am trying to use your package to interpret a gbm model (MODELO) but some variables have missing values NA. When I use the descompose function it appears an error:

**decompose_gbm_prediction(gbm = MODELO, prediction_row = TABLA[1, ])**

_Error in if (!is.na(cat_value) && cat_value != "NA") { : 
  missing value where TRUE/FALSE needed_

Do you know how could I solve it in order that missing values can be considered.

Thanks in advance.

**Comment by richardangell** [comment]
Hi @adriasebastia thanks for your interest. Can you provide a small reproducible example?

**Comment by richardangell** [comment]
Fixed in #23
